### ISSUE TITLE
packagemanager not showing available updates

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/existdb-packagemanager#1]
old: 
![screenshot 2017-12-20 14 26 09](https://user-images.githubusercontent.com/6205362/34209311-e6b091c6-e591-11e7-9f41-ea9cb07d006b.png)

new:
![screenshot 2017-12-20 14 26 34](https://user-images.githubusercontent.com/6205362/34209325-f12b7ce2-e591-11e7-9070-d1331569c013.png)

If users need to click on the pink plus sign to check for updates, we should tell them:
![screenshot 2017-12-20 14 29 50](https://user-images.githubusercontent.com/6205362/34209415-591fa72e-e592-11e7-83e4-d9ab6478a3f0.png)

**Comment by adamretter** [comment]
I also mentioned such behaviour in a community call a few weeks back. Good to have the issue to track it.

**Comment by JoernT** [comment]
yes that's true. For efficiency i load just the local list (which doesn't know about the updates). But certainly that is a most-wanted feature - will look into it.

**Comment by JoernT** [comment]
Implemented a rather simple solution for now - showing a toast with an 'install' button in case there are updated. Clicking the button will switch to the 'available' page.

This could be more sophisticated but that's significantly harder to implement in the current architecture.
