### ISSUE TITLE
Package manager extremely slow with Safari

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/existdb-packagemanager#12]
In plain eXist-db v5, the default package manager is extremely slow, and unusable, with Safari.

Please could you check why this is?

**Comment by dizzzz** [comment]
after some time it looks to get more usable (though a lot of stops);

this is one of the two messages that pops up:

<img width="722" alt="image" src="https://user-images.githubusercontent.com/1700062/56443579-9bafa580-62f5-11e9-8af3-b86b2840d93c.png">

the other message is about 'slowing down the browser'

**Comment by dizzzz** [comment]
<img width="759" alt="image" src="https://user-images.githubusercontent.com/1700062/56443685-fa751f00-62f5-11e9-9814-9bebb21c0e80.png">

when this is reported the browser is very slow and sluggish

**Comment by wolfgangmm** [comment]
@dizzzz which OSX version are you running? Using macOS 10.14.5 I can't see any performance issues. I have also not observed sluggishness on other people's machines.

In general, all major browsers have been caching up on native webcomponent support during the last months, so it's likely that newer versions offer a much better experience than older ones.

**Comment by dizzzz** [comment]
macOS 10.14.6  // safari 12.1.2 (current state) but the issues were there even before I reported it on Mid April. It has been slow for me from the beginning...

**Comment by wolfgangmm** [comment]
Ok, I'm really unable to reproduce this and safari also seems to behave well with other apps based on web components. Could it be some browser plugin interfering?

If other users have the same issue, please report here...

**Comment by dizzzz** [comment]
I will re-check my plugins....

**Comment by duncdrum** [comment]
i see the same thing

**Comment by dizzzz** [comment]
@duncdrum the same slow-down? or the same normal performance?

**Comment by JoernT** [comment]
checked on my machine...

On first startup of Safari (which i use rarely) i had NO dev tools activated and i could not see packagemanager list (or extremely slow maybe) - after activating dev tools it suddenly loaded very quickly. Couldn't reproduce slow loading after that any more.

**Comment by duncdrum** [comment]
@dizzzz same slow down, current macOS and safari, but has happened for a while.  No dev pane open. Workaround: don t use safari (also checked with tech preview)

**Comment by dizzzz** [comment]
It looks like that having a content (ad) blockert running might cause the issue; switching it off helps to get better performance!

**Comment by joewiz** [comment]
@dizzzz For the record, which content / ad blocker was it, if I might ask?

**Comment by dizzzz** [comment]
I use "1Blocker" https://1blocker.com
