### ISSUE TITLE
Suggestions for naming of repo and app

### ISSUE THREAD

**Issue by joewiz** [eXist-db/existdb-packagemanager#4]
1. Remove the `existdb-` prefix, which is redundant now that the repository belongs to the eXist-db organization.  (If a package is for eXist and only pertains to eXist, the prefix is redundant, e.g., `documentation`, `demo` do not have the prefix.  The only time `exist-` or `existdb-` should be considered be used is when a package is an eXist-specific implementation of or service for another piece of software, such as `atom-existdb` or `exist-domts`; even so, by virtue of a repository belonging to the eXist-db organization, the prefix can be omitted, e.g., `mvn-repo`.  These prefixes and names also pollute the listing of the public-repo; this app should be under "P" not "E".)
2. Change the "abbreviated" name to "package-manager" (or "packages"), because merging these two words together without punctuation is hard to read.

The changes would result in the following:

1. Repo name: `package-manager`
2. repo.xml
  - `<description>Package Manager</description>`
  - `<website>https://github.com/eXist-db/package-manager</website>`
  - `<target>package-manager</target>`
3. expath-pkg.xml
  - `name="http://exist-db.org/apps/package-manager"`
  - `abbrev="package-manager"`
  - `<title>Package Manager</title>`

I would suggest the same for the Packageservice:

  - existdb-packageservice --> package-service
  - existdb Packageservice --> Package Service

I would also suggest the same for the Usermanager:

  - usermanager --> user-manager
  - Usermanager --> User Manager

**Comment by JoernT** [comment]
Though i see the point this is rather laborious for the effect. The naming has some history: as these apps make use of Web Components (which are defined by having a '-' in their name) i've choosen 'existdb-' as the prefix. The apps were originally developed in private (on our gitlab) and then moved to github. That's why the names persisted. 

However i'll keep this in mind for the future but it's not as easy as changing the repo names.

**Comment by joewiz** [comment]
@JoernT Thanks for your reply. Certainly, the Web Component naming convention must be adhered to for the web component resources (e.g., the filename `existdb-packagemanager.html` and its corresponding `<existdb-packagemanager>` component referenced in `index.html`. Is there a technical reason that the git repository name must retain the "existdb-" prefix?

**Comment by JoernT** [comment]
@joe i guess not. That can be renamed i think.

**Comment by JoernT** [comment]
while component renaming is not unreasonable it's work that i'd like to avoid for now. However the repo-name has changed to 'packagemanager'. We can re-consider other changes later again. Closing for now
