### ISSUE TITLE
packagemanager raises error for `-SNAPSHOT`

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/existdb-packagemanager#5]
trying to install a dev-version of my app into a new exist with package manager `4.0.5` now raises the following error both on screen and in the `exist.log`

```
ERROR (Deploy.java [installAndDeployFromDb]:215) - Invalid SemVer pattern '0.1-SNAPSHOT': second part is not a number 
org.expath.pkg.repo.PackageException: Invalid SemVer pattern '0.1-SNAPSHOT': second part is not a number
	at org.expath.pkg.repo.deps.Semver.parseError(Semver.java:214) ~[pkg-java-fork.jar:?]
	at org.expath.pkg.repo.deps.Semver.parse(Semver.java:189) ~[pkg-java-fork.jar:?]
	at org.expath.pkg.repo.deps.Semver.<init>(Semver.java:37) ~[pkg-java-fork.jar:?]
…
```

since SNAPSHOT is standard for maven I'd say this is a bug, and it should accept SNAPSHOT as part of the server

**Comment by joewiz** [comment]
SNAPSHOT isn’t the problem. Semver requires 3 numbers; you only have 2: https://semver.org/#spec-item-2.
